webdriver.driver=chrome
serenity.retry.tests=2
serenity.project.name=Demo Project using Serenity and Cucumber
chrome.switches=--start-maximized;--headless;--no-sandbox;--disable-dev-shm-usage;--disable-gpu;--window-size=1920,1080
webdriver.timeouts.implicitlywait=10000
serenity.take.screenshots=AFTER_EACH_STEP
serenity.verbose.steps=false
serenity.report.encoding=UTF8
feature.file.encoding=UTF8
serenity.test.root=co.com.certification.orangetest